- src: git+https://github.com/wikitops/ansible_epel
  version: "1.3"
  name: epel

- src: git+https://github.com/wikitops/ansible_pip
  version: "1.3"
  name: pip

- src: git+https://github.com/wikitops/ansible_docker
  version: "1.5"
  name: docker
